version: "3.9"

services:
  # Redis service
  redis:
    image: redis:8-alpine
    container_name: redis_server
    ports:
      - "6379:6379"

  # Backend service
  backend:
    build: ./backend
    container_name: mern_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app             # Live code changes
      - /app/node_modules          # Persist node_modules
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=5000
    depends_on:
      - redis
    command: npx nodemon -L server.js

  # Frontend service
  frontend:
    build: ./frontend
    container_name: mern_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
    command: npm run dev
